openapi: 3.0.3
info:
  title: Ping API
  version: "1.0.0"
paths:
  /ping:
    get:
      summary: Vérifie la disponibilité du service
      responses:
        '200':
          description: Retourne pong
          content:
            text/plain:
              schema:
                type: string
              example: pong
              
