openapi: 3.0.0
info:
  title: API de Produits et Commandes
  version: 1.0.0
  description: API pour gérer des produits et des commandes avec authentification.

tags:
  - name: Products
    description: Opérations sur les produits
  - name: Orders
    description: Opérations sur les commandes

paths:
  /products:
    get:
      tags:
        - Products
      summary: Recherche de produits
      description: Retourne une liste de produits.
      responses:
        '200':
          description: Une liste de produits.
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Product'

  /orders:
    get:
      tags:
        - Orders
      summary: Liste paginée des commandes
      parameters:
        - $ref: '#/components/parameters/PageParam'
        - $ref: '#/components/parameters/SizeParam'
      responses:
        '200':
          description: Une liste paginée de commandes.
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Order'
    post:
      tags:
        - Orders
      summary: Créer une commande
      security:
        - BasicAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Order'
            examples:
              newOrder:
                summary: Exemple de nouvelle commande
                value:
                  customer_name: "John Doe"
                  total_amount: 199.99
      responses:
        '201':
          description: Commande créée avec succès.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Order'
              examples:
                createdOrder:
                  summary: Commande créée
                  value:
                    identifier: 101
                    customer_name: "John Doe"
                    creation_datetime: "2024-08-22T10:30:00Z"
                    total_amount: 199.99

components:
  schemas:
    Product: 
      type: object
      properties:
        name:
          type: string
        expiration_datetime:
          type: string
          format: date-time
        price:
          type: number
          format: float
    Order:
      type: object
      properties:
        identifier:
          type: integer
          readOnly: true
        customer_name:
          type: string
        creation_datetime:
          type: string
          format: date-time
          readOnly: true
        total_amount:
          type: number
          format: float

  parameters:
    PageParam:
      name: page
      in: query
      description: Numéro de la page
      schema:
        type: integer
        default: 1
    SizeParam:
      name: size
      in: query
      description: Nombre d'éléments par page
      schema:
        type: integer
        default: 20

  securitySchemes:
    BasicAuth:
      type: http
      scheme: basic
